# Generated by Django 2.2.4 on 2019-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190809_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
