# Generated by Django 2.2.4 on 2019-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagemperfil',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
