# Generated by Django 2.2.4 on 2019-08-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentarios_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFromPosts', to='posts.Posts', verbose_name='posts'),
        ),
    ]
